export const editableFields = [
  'nickname',
  'nickname_en',
  'phone',
  'emergency_phone',
  'line_id',
  'instagram',
  'facebook',
  'other_contact',
  'food_allergy',
  'disease',
  'drug_allergy',
  'public_profile',
  'show_instagram',
  'show_line_id',
] as const;

export const fieldLabels: Record<string, string> = {
  email: 'อีเมล',
  student_id: 'รหัสนักศึกษา',
  name_th: 'ชื่อภาษาไทย',
  name_en: 'ชื่อภาษาอังกฤษ',
  nickname: 'ชื่อเล่น',
  nickname_en: 'ชื่อเล่นภาษาอังกฤษ',
  major: 'สาขา',
  phone: 'เบอร์โทร',
  emergency_phone: 'เบอร์ติดต่อฉุกเฉิน',
  line_id: 'Line ID',
  instagram: 'Instagram',
  facebook: 'Facebook',
  other_contact: 'ช่องทางติดต่ออื่น',
  food_allergy: 'แพ้อาหาร',
  disease: 'โรคประจำตัว',
  drug_allergy: 'แพ้ยา',
  admission_round: 'รอบการรับเข้า',
  gender: 'เพศ',
  hometown: 'จังหวัด/ภูมิลำเนา',
  interests: 'ความสนใจ',
  public_profile: 'เปิดโปรไฟล์สาธารณะ',
  show_instagram: 'แสดง Instagram',
  show_line_id: 'แสดง Line ID',
};

export const fieldLabelsEn: Record<string, string> = {
  email: 'Email',
  student_id: 'Student ID',
  name_th: 'Thai name',
  name_en: 'English name',
  nickname: 'Nickname',
  nickname_en: 'English nickname',
  major: 'Major',
  phone: 'Phone',
  emergency_phone: 'Emergency phone',
  line_id: 'Line ID',
  instagram: 'Instagram',
  facebook: 'Facebook',
  other_contact: 'Other contact',
  food_allergy: 'Food allergy',
  disease: 'Medical condition',
  drug_allergy: 'Drug allergy',
  admission_round: 'Admission round',
  gender: 'Gender',
  hometown: 'Hometown / province',
  interests: 'Interests',
  public_profile: 'Public profile',
  show_instagram: 'Show Instagram',
  show_line_id: 'Show Line ID',
};

export function fieldLabel(field: string, language: 'th' | 'en' = 'th') {
  return (language === 'th' ? fieldLabels : fieldLabelsEn)[field] ?? field;
}

export const sensitiveFields = [
  'email',
  'phone',
  'emergency_phone',
  'line_id',
  'instagram',
  'facebook',
  'other_contact',
  'food_allergy',
  'disease',
  'drug_allergy',
];
