export const copy = {
  th: {
    hiddenForPrivacy: 'ซ่อนเพื่อความเป็นส่วนตัว',
    participants: 'ผู้เข้าร่วม',
    myInformation: 'ข้อมูลของฉัน',
    staff: 'ทีมงาน',
    staffCheckIn: 'เช็กชื่อทีมงาน',
    emergency: 'เหตุฉุกเฉิน',
    adminCommandCenter: 'ศูนย์ควบคุมระบบ',
    documentCenter: 'ศูนย์เอกสาร',
    dataHealth: 'ตรวจสุขภาพข้อมูล',
    systemReadiness: 'ตรวจความพร้อมระบบ',
    editRequests: 'คำขอแก้ไขข้อมูล',
    updateRequests: 'คำร้องแก้ข้อมูล',
    duplicateCheck: 'ตรวจข้อมูลซ้ำ',
    tryNicknameOrMajor: 'ลองค้นด้วยชื่อเล่น สาขา หรือคำที่ใกล้เคียง',
    tryPublicSearch: 'ยังไม่พบรายชื่อที่ตรงกัน ลองล้างตัวกรองหรือค้นหาด้วยชื่อเล่น สาขา หรือชื่อภาษาอังกฤษ',
    importCommit: 'นำเข้าข้อมูลจริง',
    syncStaffRoster: 'ซิงค์ข้อมูลทีมงาน',
    staffLogin: 'เข้าสู่ระบบทีมงาน',
    staffAccount: 'บัญชีทีมงาน',
    staffHome: 'หน้าทีมงาน',
    adminDashboard: 'ศูนย์ควบคุมระบบ',
    clearFilters: 'ล้างตัวกรอง',
    loadingData: 'กำลังโหลดข้อมูล',
    noDataYet: 'ยังไม่มีข้อมูล',
    noFilterResults: 'ไม่พบข้อมูลที่ตรงกับตัวกรอง',
    tryAnotherSearch: 'ลองค้นหาด้วยคำอื่น',
    saved: 'บันทึกแล้ว',
    saveFailed: 'บันทึกไม่สำเร็จ กรุณาลองใหม่',
    requestSubmitted: 'ส่งคำขอแล้ว',
    waitingForReview: 'รอตรวจสอบ',
    approved: 'อนุมัติ',
    rejected: 'ปฏิเสธ',
    viewDetails: 'ดูรายละเอียด',
    manage: 'จัดการ',
    more: 'เพิ่มเติม',
    export: 'ส่งออก',
    exportData: 'ส่งออกข้อมูล',
    moreActions: 'การทำงานเพิ่มเติม',
    generatedRememberSave: 'จัดกลุ่มใหม่แล้ว อย่าลืมกดบันทึก',
    medicalVisible: 'ข้อมูลที่ต้องดูแลเป็นพิเศษ',
    clearGroups: 'ลบการจัดกลุ่มทั้งหมด',
  },
  en: {
    hiddenForPrivacy: 'Hidden for privacy',
    participants: 'Participants',
    myInformation: 'My information',
    staff: 'Staff',
    staffCheckIn: 'Staff check-in',
    emergency: 'Emergency',
    adminCommandCenter: 'Admin Command Center',
    documentCenter: 'Document Center',
    dataHealth: 'Data Health',
    systemReadiness: 'System Readiness',
    editRequests: 'Edit requests',
    updateRequests: 'Update requests',
    duplicateCheck: 'Duplicate check',
    tryNicknameOrMajor: 'Try a nickname, major, or similar keyword.',
    tryPublicSearch: 'No matching participants found. Try clearing filters or searching by nickname, major, or English name.',
    importCommit: 'Commit import',
    syncStaffRoster: 'Sync staff roster',
    staffLogin: 'Staff sign in',
    staffAccount: 'Staff account',
    staffHome: 'Staff home',
    adminDashboard: 'Admin Command Center',
    clearFilters: 'Clear filters',
    loadingData: 'Loading data',
    noDataYet: 'No data yet',
    noFilterResults: 'No records match your filters',
    tryAnotherSearch: 'Try another search',
    saved: 'Saved',
    saveFailed: 'Could not save. Please try again.',
    requestSubmitted: 'Request submitted',
    waitingForReview: 'Waiting for review',
    approved: 'Approved',
    rejected: 'Rejected',
    viewDetails: 'View details',
    manage: 'Manage',
    more: 'More',
    export: 'Export',
    exportData: 'Export data',
    moreActions: 'More actions',
    generatedRememberSave: 'Groups regenerated. Remember to save.',
    medicalVisible: 'Needs special care',
    clearGroups: 'Clear all groups',
  },
};

export type CopyLanguage = keyof typeof copy;
