export type GuideAudience = 'participant' | 'staff' | 'admin' | 'emergency';

export type GuideProblem = {
  problem: string;
  solution: string;
};

export type GuideFieldNote = {
  label: string;
  description: string;
};

export type GuideTopic = {
  topicId: string;
  id: string;
  category: string;
  slug: string;
  titleTh: string;
  titleEn: string;
  summaryTh: string;
  summaryEn: string;
  audience: GuideAudience[];
  relatedRoutes?: string[];
  keywordsTh?: string[];
  keywordsEn?: string[];
  quickHelpTh?: string;
  quickHelpEn?: string;
  whenToUseTh?: string[];
  whenToUseEn?: string[];
  stepsTh: string[];
  stepsEn: string[];
  fieldNotesTh?: GuideFieldNote[];
  fieldNotesEn?: GuideFieldNote[];
  tipsTh?: string[];
  tipsEn?: string[];
  commonProblemsTh?: GuideProblem[];
  commonProblemsEn?: GuideProblem[];
  relatedTopicIds?: string[];
};

export type GuideCategory = {
  id: string;
  titleTh: string;
  titleEn: string;
  descriptionTh: string;
  descriptionEn: string;
  audience: GuideAudience[];
};

export const guideCategories: GuideCategory[] = [
  {
    id: 'events',
    titleTh: 'ระบบหลายกิจกรรม',
    titleEn: 'Multi-Event Platform',
    descriptionTh: 'แนวคิดกิจกรรมหลายงาน การลงทะเบียนกิจกรรมใหม่ และการสมัครสตาฟ',
    descriptionEn: 'Concepts for multiple events, future registration, and staff application flows.',
    audience: ['participant', 'staff', 'admin'],
  },
  {
    id: 'participant',
    titleTh: 'ผู้เข้าร่วมกิจกรรม',
    titleEn: 'Participants',
    descriptionTh: 'ค้นหารายชื่อ ตรวจสอบข้อมูล และดูข้อมูลกลุ่มอย่างปลอดภัย',
    descriptionEn: 'Search participants, verify information, and view group details safely.',
    audience: ['participant'],
  },
  {
    id: 'staff',
    titleTh: 'ทีมงาน',
    titleEn: 'Staff',
    descriptionTh: 'เข้าสู่ระบบ แก้โปรไฟล์ และใช้ QR ส่วนตัวของทีมงาน',
    descriptionEn: 'Sign in, manage staff profiles, and use staff personal QR.',
    audience: ['staff'],
  },
  {
    id: 'staff-attendance',
    titleTh: 'เช็กชื่อทีมงาน',
    titleEn: 'Staff Attendance',
    descriptionTh: 'คู่มือเช็กชื่อด้วย QR กล้อง และตัวตนทีมงานที่จำไว้ในเครื่อง',
    descriptionEn: 'Guides for QR check-in, camera scan, and remembered staff identity.',
    audience: ['staff', 'admin'],
  },
  {
    id: 'admin',
    titleTh: 'ผู้ดูแลระบบ',
    titleEn: 'Admin',
    descriptionTh: 'จัดการ Dashboard รายชื่อ กลุ่ม ทีมงาน และข้อมูลกิจกรรม',
    descriptionEn: 'Manage dashboards, participants, groups, staff, and event data.',
    audience: ['admin'],
  },
  {
    id: 'admin-attendance',
    titleTh: 'จัดการเช็กชื่อ',
    titleEn: 'Admin Attendance',
    descriptionTh: 'สร้างรอบเช็กชื่อ แสดง QR เช็กชื่อ Manual และ Export',
    descriptionEn: 'Create sessions, show QR, use manual fallback, and export reports.',
    audience: ['admin'],
  },
  {
    id: 'documents',
    titleTh: 'ศูนย์เอกสาร',
    titleEn: 'Document Center',
    descriptionTh: 'ตั้งค่าโครงการ อัปโหลด DOCX template และสร้างเอกสาร',
    descriptionEn: 'Set project data, upload DOCX templates, and generate documents.',
    audience: ['admin'],
  },
  {
    id: 'emergency',
    titleTh: 'ระบบฉุกเฉิน',
    titleEn: 'Emergency',
    descriptionTh: 'ใช้ข้อมูลสุขภาพและเหตุฉุกเฉินเฉพาะผู้มีสิทธิ์',
    descriptionEn: 'Use emergency and health information only with authorized access.',
    audience: ['emergency', 'admin'],
  },
  {
    id: 'faq',
    titleTh: 'คำถามที่พบบ่อย',
    titleEn: 'FAQ',
    descriptionTh: 'คำตอบสั้น ๆ สำหรับปัญหาที่เจอบ่อยระหว่างใช้งานจริง',
    descriptionEn: 'Short answers for common real-event issues.',
    audience: ['participant', 'staff', 'admin', 'emergency'],
  },
];

const attendeePrivacyTh = 'หน้าสาธารณะจะแสดงเฉพาะข้อมูลจำเป็น เช่น ชื่อ สาขา และกลุ่ม ข้อมูลติดต่อและสุขภาพถูกซ่อนไว้';
const attendeePrivacyEn = 'Public pages show only necessary fields such as name, major, and group. Contact and health data stay hidden.';

export const guideTopics: GuideTopic[] = [
  {
    topicId: 'events.overview',
    id: 'events.overview',
    category: 'events',
    slug: 'overview',
    titleTh: 'ระบบหลายกิจกรรมคืออะไร',
    titleEn: 'What Is the Multi-Event Platform?',
    summaryTh: 'ระบบจะแยกข้อมูลตัวบุคคลออกจากข้อมูลของแต่ละกิจกรรม เพื่อใช้ข้อมูลเดิมซ้ำได้อย่างปลอดภัย',
    summaryEn: 'The platform separates person identity from event participation so known data can be reused safely.',
    audience: ['participant', 'staff', 'admin'],
    relatedRoutes: ['/guide'],
    keywordsTh: ['หลายกิจกรรม', 'event', 'คน', 'ลงทะเบียน', 'สมัครสตาฟ', 'prefill'],
    keywordsEn: ['multi-event', 'event', 'people', 'registration', 'staff application', 'prefill'],
    quickHelpTh: 'ในอนาคต คนหนึ่งคนจะมีข้อมูลพื้นฐานชุดเดียว แต่สามารถสมัคร/เข้าร่วมได้หลายกิจกรรม',
    quickHelpEn: 'In the future, one person keeps one base identity while joining or staffing many events.',
    whenToUseTh: ['เมื่อเริ่มเปิดกิจกรรมใหม่', 'เมื่อต้องการใช้ข้อมูลนักศึกษาปี 2 เดิมเพื่อลดการกรอกซ้ำ'],
    whenToUseEn: ['When opening a new event.', 'When reusing known Engineering year 2 data to reduce repeated form filling.'],
    stepsTh: ['เลือกกิจกรรมที่ต้องการ', 'ระบบใช้ข้อมูลบุคคลเดิมถ้าพบ', 'ตอบเฉพาะคำถามของกิจกรรมนั้น', 'ติดตามสถานะในกิจกรรมที่เลือก'],
    stepsEn: ['Choose an event.', 'The system reuses known person data if found.', 'Answer only event-specific questions.', 'Track status inside the selected event.'],
    fieldNotesTh: [
      { label: 'ข้อมูลบุคคล', description: 'ชื่อ รหัสนักศึกษา สาขา เบอร์ อีเมล ที่ใช้ซ้ำข้ามกิจกรรม' },
      { label: 'ข้อมูลกิจกรรม', description: 'การสมัคร กลุ่ม หน้าที่ สถานะเช็กชื่อ และคำตอบเฉพาะกิจกรรม' },
    ],
    fieldNotesEn: [
      { label: 'Person data', description: 'Name, student ID, major, phone, and email reused across events.' },
      { label: 'Event data', description: 'Registration, group, role, attendance, and event-specific answers.' },
    ],
    tipsTh: ['ระบบปัจจุบันยังใช้กิจกรรม default คือ สานสัมพันธ์ 69 อยู่', 'การ migrate จริงควรทำแบบเพิ่มตารางใหม่และ fallback กลับกิจกรรมเดิมได้'],
    tipsEn: ['The current app still uses the default Entaneer Bonding 69 event.', 'Real migration should be additive and keep fallback to the current event.'],
    commonProblemsTh: [
      { problem: 'กลัวข้อมูลกิจกรรมปนกัน', solution: 'ต้องมี event_id และ event switcher ก่อนเปิดใช้หลายกิจกรรมจริง' },
    ],
    commonProblemsEn: [
      { problem: 'Event data might mix.', solution: 'Add event_id and event switcher before real multi-event operations.' },
    ],
    relatedTopicIds: ['events.registration', 'events.staff-application', 'faq.no-auth-staff'],
  },
  {
    topicId: 'events.registration',
    id: 'events.registration',
    category: 'events',
    slug: 'registration',
    titleTh: 'การลงทะเบียนกิจกรรมใหม่',
    titleEn: 'Registering for a New Event',
    summaryTh: 'ผู้เข้าร่วมที่อยู่ในฐานข้อมูลเดิมควรตรวจพบตัวตนและกรอกเฉพาะคำถามของกิจกรรมใหม่',
    summaryEn: 'Known participants should be matched from existing data and answer only new event-specific questions.',
    audience: ['participant', 'admin'],
    keywordsTh: ['ลงทะเบียนกิจกรรม', 'prefill', 'ยืนยันตัวตน', 'student id', 'กิจกรรมใหม่'],
    keywordsEn: ['event registration', 'prefill', 'identity verification', 'student id', 'new event'],
    quickHelpTh: 'ระบบควรถามรหัสนักศึกษา/อีเมล/เบอร์ แล้วเติมชื่อ สาขา ชั้นปีให้อัตโนมัติถ้าพบข้อมูลเดิม',
    quickHelpEn: 'The system should ask for student ID/email/phone, then prefill name, major, and year if known.',
    stepsTh: ['เปิดหน้ากิจกรรม', 'กดลงทะเบียนเข้าร่วม', 'ยืนยันตัวตนด้วยรหัสนักศึกษา อีเมล หรือเบอร์โทร', 'ตรวจข้อมูลพื้นฐานที่ระบบเติมให้', 'ตอบคำถามเฉพาะกิจกรรมและส่งข้อมูล'],
    stepsEn: ['Open the event page.', 'Click participant registration.', 'Verify with student ID, email, or phone.', 'Review prefilled base data.', 'Answer event-specific questions and submit.'],
    tipsTh: ['lookup สาธารณะควรบอกแค่ว่าพบข้อมูล ไม่ควรเผยเบอร์หรืออีเมลเต็ม', 'ถ้าไม่พบข้อมูล ให้แสดงทางเลือกตามนโยบายกิจกรรมนั้น'],
    tipsEn: ['Public lookup should only confirm a match, not reveal full phone or email.', 'If not found, show options based on event policy.'],
    commonProblemsTh: [
      { problem: 'ชื่อ/สาขาเก่าไม่ถูกต้อง', solution: 'ให้แก้ช่องทางติดต่อได้ทันที แต่ข้อมูล identity สำคัญควรรอแอดมินตรวจ' },
    ],
    commonProblemsEn: [
      { problem: 'Known name/major is outdated.', solution: 'Allow contact updates, but require admin review for identity fields.' },
    ],
    relatedTopicIds: ['events.overview', 'participant.edit-info'],
  },
  {
    topicId: 'events.staff-application',
    id: 'events.staff-application',
    category: 'events',
    slug: 'staff-application',
    titleTh: 'การสมัครสตาฟกิจกรรมใหม่',
    titleEn: 'Applying as Staff for a New Event',
    summaryTh: 'ผู้สมัครสตาฟใช้ข้อมูลพื้นฐานเดิม แล้วตอบเฉพาะทีม/หน้าที่/เวลาว่าง/ประสบการณ์ของกิจกรรมใหม่',
    summaryEn: 'Staff applicants reuse base identity data and answer only role, team, availability, and motivation questions for the new event.',
    audience: ['staff', 'admin'],
    keywordsTh: ['สมัครสตาฟ', 'staff application', 'ทีม', 'หน้าที่', 'availability', 'motivation'],
    keywordsEn: ['staff application', 'team', 'role', 'availability', 'motivation'],
    quickHelpTh: 'การสมัครสตาฟไม่ควรเป็นการให้สิทธิ์ทันที ต้องมีสถานะรอแอดมินตรวจและอนุมัติ',
    quickHelpEn: 'A staff application should not grant access immediately; it should wait for admin review and approval.',
    stepsTh: ['เปิดหน้ากิจกรรม', 'กดสมัครเป็นทีมงาน', 'ยืนยันตัวตนหรือกรอกข้อมูลพื้นฐานถ้าไม่พบ', 'เลือกทีม/หน้าที่ที่สนใจ', 'กรอกเวลาว่าง ประสบการณ์ เหตุผล และส่งใบสมัคร'],
    stepsEn: ['Open the event page.', 'Click apply as staff.', 'Verify identity or enter base data if not found.', 'Choose preferred team/role.', 'Enter availability, experience, motivation, and submit.'],
    fieldNotesTh: [
      { label: 'preferred_team', description: 'ทีม/ฝ่ายที่อยากทำในกิจกรรมนี้' },
      { label: 'availability', description: 'เวลาว่างเฉพาะกิจกรรมนี้ ไม่ใช่ข้อมูลถาวรของบุคคล' },
      { label: 'status', description: 'submitted/reviewed/approved/rejected ตามการตรวจของแอดมิน' },
    ],
    fieldNotesEn: [
      { label: 'preferred_team', description: 'Preferred team for this event.' },
      { label: 'availability', description: 'Availability for this event only, not permanent person data.' },
      { label: 'status', description: 'submitted/reviewed/approved/rejected based on admin review.' },
    ],
    tipsTh: ['แยก staff application ออกจาก staff access จริง', 'คนเดิมอาจเป็นสตาฟกิจกรรมนี้ แต่เป็นผู้เข้าร่วมกิจกรรมอื่นได้'],
    tipsEn: ['Keep staff application separate from actual staff access.', 'The same person may be staff in one event and participant in another.'],
    commonProblemsTh: [
      { problem: 'สมัครแล้วเข้า Staff Mode ไม่ได้', solution: 'ต้องรอแอดมินอนุมัติและเพิ่ม event role ก่อน' },
    ],
    commonProblemsEn: [
      { problem: 'I applied but cannot enter Staff Mode.', solution: 'Admin must approve and grant an event role first.' },
    ],
    relatedTopicIds: ['events.overview', 'staff.login', 'staff.profile-verify'],
  },
  {
    topicId: 'participant.search',
    id: 'participant.search',
    category: 'participant',
    slug: 'search',
    titleTh: 'ค้นหารายชื่อผู้เข้าร่วม',
    titleEn: 'Search Participants',
    summaryTh: 'ค้นหาชื่อ ชื่อเล่น สาขา และกลุ่มของตัวเองจากหน้าหลัก',
    summaryEn: 'Find your name, nickname, major, and group from the public list.',
    audience: ['participant'],
    relatedRoutes: ['/'],
    keywordsTh: ['ค้นหา', 'รายชื่อ', 'ชื่อเล่น', 'สาขา', 'กลุ่ม', 'คิวอาร์', 'public'],
    keywordsEn: ['search', 'participant', 'name', 'nickname', 'major', 'group', 'public'],
    quickHelpTh: 'พิมพ์ชื่อ ชื่อเล่น หรือสาขา แล้วใช้ตัวกรองสี/กลุ่มย่อยเพื่อเจอรายชื่อเร็วขึ้น',
    quickHelpEn: 'Type a name, nickname, or major, then use color/subgroup filters to narrow results.',
    whenToUseTh: ['เมื่ออยากดูว่าชื่อของตัวเองอยู่ในระบบหรือยัง', 'เมื่อต้องการดูสีหรือกลุ่มย่อยแบบไม่เปิดเผยข้อมูลส่วนตัว'],
    whenToUseEn: ['When you want to confirm your registration appears in the system.', 'When you need color or subgroup details without exposing private data.'],
    stepsTh: ['เปิดหน้าหลัก', 'พิมพ์ชื่อ ชื่อเล่น หรือสาขาในช่องค้นหา', 'กดตัวกรองเพื่อเลือกสาขา สี หรือกลุ่มย่อย', 'แตะการ์ดรายชื่อเพื่อดูข้อมูลแบบปลอดภัย'],
    stepsEn: ['Open the home page.', 'Type a name, nickname, or major in search.', 'Use filters for major, color, or subgroup.', 'Tap a participant card to view privacy-safe details.'],
    fieldNotesTh: [
      { label: 'ช่องค้นหา', description: 'ค้นหาได้หลายคำ เช่น ชื่อจริง ชื่อเล่น หรือรหัสสาขา' },
      { label: 'ตัวกรอง', description: 'ใช้ลดจำนวนผลลัพธ์ โดยเฉพาะบนมือถือที่หน้าจอเล็ก' },
    ],
    fieldNotesEn: [
      { label: 'Search', description: 'Search by legal name, nickname, or major code.' },
      { label: 'Filters', description: 'Narrow results, especially on smaller phone screens.' },
    ],
    tipsTh: [attendeePrivacyTh, 'ถ้าหาชื่อไม่เจอ ลองล้างตัวกรองและค้นหาด้วยชื่อเล่น'],
    tipsEn: [attendeePrivacyEn, 'If you cannot find a name, clear filters and try a nickname.'],
    commonProblemsTh: [
      { problem: 'ค้นหาแล้วไม่เจอชื่อ', solution: 'ล้างตัวกรอง ลองสะกดชื่อเล่น หรือใช้หน้าแก้ไขข้อมูลเพื่อตรวจสอบตัวตน' },
      { problem: 'ต้องการดูเบอร์โทรหรือข้อมูลสุขภาพ', solution: 'ข้อมูลเหล่านี้ไม่แสดงในหน้าสาธารณะเพื่อความเป็นส่วนตัว' },
    ],
    commonProblemsEn: [
      { problem: 'No matching name appears.', solution: 'Clear filters, try a nickname, or verify through Edit Info.' },
      { problem: 'I need phone or health details.', solution: 'Those fields are intentionally hidden on public pages.' },
    ],
    relatedTopicIds: ['participant.edit-info', 'participant.my-group'],
  },
  {
    topicId: 'participant.edit-info',
    id: 'participant.edit-info',
    category: 'participant',
    slug: 'edit-info',
    titleTh: 'ตรวจสอบและแก้ไขข้อมูลของฉัน',
    titleEn: 'Verify and Edit My Information',
    summaryTh: 'ยืนยันด้วยอีเมลและเบอร์โทร แล้วส่งคำขอแก้ไขให้แอดมินอนุมัติ',
    summaryEn: 'Verify by email and phone, then submit an edit request for admin approval.',
    audience: ['participant'],
    relatedRoutes: ['/edit'],
    keywordsTh: ['แก้ไขข้อมูล', 'แก้ข้อมูล', 'ยืนยันตัวตน', 'อีเมล', 'เบอร์โทร', 'อนุมัติ'],
    keywordsEn: ['edit info', 'verification', 'email', 'phone', 'approval', 'request'],
    quickHelpTh: 'กรอกอีเมลและเบอร์โทรที่ใช้ลงทะเบียน จากนั้นแก้เฉพาะช่องที่ต้องการเปลี่ยน',
    quickHelpEn: 'Enter the email and phone used during registration, then edit only the fields you want to change.',
    whenToUseTh: ['เมื่อข้อมูลติดต่อหรือสุขภาพผิด', 'เมื่อต้องการเปิด/ปิดการแสดงโปรไฟล์กับเพื่อนในกลุ่ม'],
    whenToUseEn: ['When contact or health information is wrong.', 'When you want to adjust friend recommendation visibility.'],
    stepsTh: ['เปิดเมนูแก้ไขข้อมูล', 'กรอกอีเมลและเบอร์โทรที่ใช้ลงทะเบียน', 'ตรวจสอบสรุปโปรไฟล์และข้อมูลกลุ่มถ้ามี', 'กรอกเฉพาะข้อมูลที่ต้องการเปลี่ยน', 'กดส่งคำขอแก้ไขและรอแอดมินอนุมัติ'],
    stepsEn: ['Open Edit Info.', 'Enter the email and phone used during registration.', 'Review the profile summary and group info if available.', 'Fill only the fields that need changes.', 'Submit the request and wait for admin approval.'],
    fieldNotesTh: [
      { label: 'อีเมล/เบอร์โทร', description: 'ใช้ยืนยันตัวตน ไม่แสดงต่อสาธารณะ' },
      { label: 'ข้อมูลสุขภาพ', description: 'เห็นเฉพาะแอดมินหรือทีมความปลอดภัยที่เกี่ยวข้อง' },
      { label: 'โปรไฟล์สาธารณะ', description: 'แสดงเฉพาะข้อมูลเบื้องต้นกับเพื่อนในกลุ่ม ไม่แสดงเบอร์โทรหรือสุขภาพ' },
    ],
    fieldNotesEn: [
      { label: 'Email/phone', description: 'Used for identity verification and not shown publicly.' },
      { label: 'Health information', description: 'Visible only to admins or authorized safety staff.' },
      { label: 'Public profile', description: 'Shows only basic friend-recommendation details, never phone or health data.' },
    ],
    tipsTh: ['ไม่ต้องกรอกทุกช่อง กรอกเฉพาะข้อมูลที่เปลี่ยน', 'ข้อมูลสำคัญบางอย่างต้องรออนุมัติเพื่อป้องกันการแก้ผิดคน'],
    tipsEn: ['You do not need to fill every field.', 'Sensitive changes require approval to prevent wrong-profile updates.'],
    commonProblemsTh: [
      { problem: 'ยืนยันตัวตนไม่ผ่าน', solution: 'ตรวจสอบว่าใช้อีเมลและเบอร์โทรเดียวกับตอนลงทะเบียน หรือติดต่อแอดมิน' },
      { problem: 'ส่งแล้วข้อมูลยังไม่เปลี่ยน', solution: 'คำขอต้องรอแอดมินตรวจสอบก่อนอัปเดตจริง' },
    ],
    commonProblemsEn: [
      { problem: 'Verification fails.', solution: 'Use the same email and phone from registration, or contact an admin.' },
      { problem: 'My data did not change immediately.', solution: 'Edit requests wait for admin review before applying.' },
    ],
    relatedTopicIds: ['participant.search', 'participant.my-group', 'faq.edit-approval-delay'],
  },
  {
    topicId: 'participant.my-group',
    id: 'participant.my-group',
    category: 'participant',
    slug: 'my-group',
    titleTh: 'ดูกลุ่มและพี่กลุ่มของตัวเอง',
    titleEn: 'View My Group and Staff',
    summaryTh: 'หลังยืนยันตัวตน ระบบจะแสดงข้อมูลกลุ่ม จุดนัดพบ และการ์ดทีมงานแบบปลอดภัย',
    summaryEn: 'After verification, the app can show your group, meeting point, and privacy-safe staff cards.',
    audience: ['participant'],
    relatedRoutes: ['/edit'],
    keywordsTh: ['กลุ่ม', 'พี่กลุ่ม', 'พี่สตาฟ', 'จุดนัดพบ', 'เพื่อนในกลุ่ม'],
    keywordsEn: ['group', 'staff', 'mentor', 'meeting point', 'friends'],
    quickHelpTh: 'ข้อมูลกลุ่มจะแสดงหลังยืนยันตัวตน ถ้ายังไม่ขึ้นยังสามารถส่งคำขอแก้ไขข้อมูลได้ตามปกติ',
    quickHelpEn: 'Group info appears after verification. If it is unavailable, you can still submit edit requests.',
    stepsTh: ['เปิดหน้าแก้ไขข้อมูล', 'ยืนยันตัวตนด้วยอีเมลและเบอร์โทร', 'ดูสี กลุ่มย่อย จุดนัดพบ และทีมงานที่เกี่ยวข้อง', 'ใช้ข้อมูลติดต่อเฉพาะที่ทีมงานเลือกเปิดเผย'],
    stepsEn: ['Open Edit Info.', 'Verify with email and phone.', 'View color, subgroup, meeting point, and related staff.', 'Use only contact channels that staff explicitly show.'],
    tipsTh: ['ข้อมูลติดต่อของทีมงานอาจถูกซ่อนถ้าเจ้าตัวยังไม่เปิดเผย', 'ระบบแนะนำเพื่อนจะแสดงเฉพาะคนที่เปิดโปรไฟล์สาธารณะ'],
    tipsEn: ['Staff contact channels may be hidden until they opt in.', 'Friend recommendations show only public profiles.'],
    commonProblemsTh: [
      { problem: 'ยังไม่เห็นกลุ่ม', solution: 'อาจยังไม่ได้จัดกลุ่มหรือระบบยังไม่เปิดเผยข้อมูล รอสักครู่หรือถามแอดมิน' },
    ],
    commonProblemsEn: [
      { problem: 'No group is shown.', solution: 'Grouping may not be released yet. You can still edit your information.' },
    ],
    relatedTopicIds: ['participant.edit-info', 'participant.search'],
  },
  {
    topicId: 'staff.login',
    id: 'staff.login',
    category: 'staff',
    slug: 'login',
    titleTh: 'เข้าสู่ระบบทีมงาน',
    titleEn: 'Staff Sign In',
    summaryTh: 'ทีมงานที่มีบัญชีเข้าสู่ระบบใช้ /login ส่วนทีมงานไม่มีบัญชีใช้ flow ยืนยันอีเมลและเบอร์โทร',
    summaryEn: 'Staff with accounts use /login. Staff without accounts use email and phone verification flows.',
    audience: ['staff'],
    relatedRoutes: ['/login', '/staff'],
    keywordsTh: ['เข้าสู่ระบบ', 'ล็อกอิน', 'ทีมงาน', 'บัญชี', 'staff'],
    keywordsEn: ['login', 'staff', 'account', 'sign in'],
    quickHelpTh: 'ใช้บัญชีทีมงานหรือแอดมินเข้าสู่ระบบ ถ้าไม่มีบัญชีให้ใช้หน้าเช็กชื่อหรือแก้โปรไฟล์แบบยืนยันตัวตน',
    quickHelpEn: 'Use a staff or admin account to sign in. Staff without accounts can use verified attendance/profile flows.',
    stepsTh: ['เปิดเมนูเข้าสู่ระบบทีมงาน', 'กรอกอีเมลและรหัสผ่าน', 'ระบบจะพาแอดมินไป Dashboard หรือทีมงานไป Staff Mode', 'ถ้าไม่มีบัญชี ให้ใช้เมนูแก้โปรไฟล์ทีมงานหรือเช็กชื่อด้วยอีเมล+เบอร์โทร'],
    stepsEn: ['Open Staff Sign In.', 'Enter email and password.', 'Admins go to Admin Dashboard; staff go to Staff Mode.', 'If you do not have an account, use verified staff profile or attendance flows.'],
    tipsTh: ['บัญชีทีมงานไม่ใช่บัญชีแอดมิน และจะเข้าเมนูแอดมินไม่ได้'],
    tipsEn: ['Staff accounts are not admin accounts and cannot access admin-only pages.'],
    commonProblemsTh: [
      { problem: 'ขึ้นว่าไม่มีสิทธิ์', solution: 'บัญชีอาจยังไม่ได้ผูกสิทธิ์ทีมงาน ให้ติดต่อแอดมิน' },
    ],
    commonProblemsEn: [
      { problem: 'The app says I have no access.', solution: 'Your account may not be linked to staff access yet. Contact an admin.' },
    ],
    relatedTopicIds: ['staff.profile-verify', 'staff-attendance.overview'],
  },
  {
    topicId: 'staff.profile-verify',
    id: 'staff.profile-verify',
    category: 'staff',
    slug: 'profile-verify',
    titleTh: 'แก้ไขโปรไฟล์ทีมงาน',
    titleEn: 'Verify and Edit Staff Profile',
    summaryTh: 'ยืนยันด้วยอีเมลและเบอร์โทรเพื่อแก้โปรไฟล์ รูป และการตั้งค่าการแสดงช่องทางติดต่อ',
    summaryEn: 'Verify by email and phone to edit staff profile, photo, and contact visibility settings.',
    audience: ['staff'],
    relatedRoutes: ['/staff/profile/verify', '/staff/profile/edit'],
    keywordsTh: ['โปรไฟล์ทีมงาน', 'แก้โปรไฟล์', 'รูปโปรไฟล์', 'avatar', 'ช่องทางติดต่อ'],
    keywordsEn: ['staff profile', 'profile verify', 'avatar', 'photo', 'contact visibility'],
    quickHelpTh: 'กรอกอีเมลและเบอร์โทรที่ลงทะเบียนทีมงาน แล้วแก้ข้อมูลที่เปิดให้แก้ได้',
    quickHelpEn: 'Enter the staff registration email and phone, then update fields that are editable.',
    stepsTh: ['เปิดหน้าแก้ไขโปรไฟล์ทีมงาน', 'กรอกอีเมลและเบอร์โทร', 'ตรวจสอบข้อมูลพื้นฐาน', 'แก้รูป โปรไฟล์ หรือช่องทางติดต่อที่ต้องการเปิดเผย', 'บันทึกหรือส่งคำขอแก้ไขตามประเภทข้อมูล'],
    stepsEn: ['Open Staff Profile Verify.', 'Enter email and phone.', 'Review basic information.', 'Update photo, profile, or contact visibility.', 'Save directly or submit a request depending on the field.'],
    fieldNotesTh: [
      { label: 'โปรไฟล์พื้นฐาน', description: 'อาจแสดงให้น้องเห็น เช่น ชื่อเล่น หน้าที่ กลุ่ม หรือ bio' },
      { label: 'ช่องทางติดต่อ', description: 'Instagram, LINE, Facebook ซ่อนไว้จนกว่าทีมงานเลือกเปิดเอง' },
      { label: 'ข้อมูลสุขภาพ', description: 'ไม่แสดงต่อสาธารณะ' },
    ],
    fieldNotesEn: [
      { label: 'Basic profile', description: 'May show nickname, role, group, or bio to participants.' },
      { label: 'Contact channels', description: 'Instagram, LINE, and Facebook stay hidden until staff opt in.' },
      { label: 'Health data', description: 'Never shown publicly.' },
    ],
    tipsTh: ['รูปโปรไฟล์ควรเป็น JPG, PNG หรือ WEBP ขนาดไม่เกิน 5 MB', 'เปิดเฉพาะช่องทางติดต่อที่พร้อมให้น้องเห็นจริง'],
    tipsEn: ['Profile photo should be JPG, PNG, or WEBP up to 5 MB.', 'Show only contact channels you are comfortable sharing.'],
    commonProblemsTh: [
      { problem: 'ยืนยันโปรไฟล์ไม่ได้', solution: 'ตรวจสอบอีเมลและเบอร์โทรที่ทีมงานใช้ลงทะเบียน หรือให้แอดมินตรวจในรายชื่อทีมงาน' },
    ],
    commonProblemsEn: [
      { problem: 'Profile verification fails.', solution: 'Check the staff registration email/phone or ask an admin to verify the staff record.' },
    ],
    relatedTopicIds: ['staff.personal-qr', 'staff-attendance.overview'],
  },
  {
    topicId: 'staff.personal-qr',
    id: 'staff.personal-qr',
    category: 'staff',
    slug: 'personal-qr',
    titleTh: 'QR ส่วนตัวทีมงาน',
    titleEn: 'Staff Personal QR',
    summaryTh: 'QR ส่วนตัวใช้ให้แอดมินสแกนเพื่อเช็กชื่อแทน ไม่ใช่ QR สำหรับเช็กชื่อด้วยตัวเอง',
    summaryEn: 'Personal QR is for admin-assisted check-in, not for self check-in.',
    audience: ['staff'],
    relatedRoutes: ['/staff/profile/qr', '/staff/attendance'],
    keywordsTh: ['QR ส่วนตัว', 'คิวอาร์ทีมงาน', 'แอดมินสแกน', 'token'],
    keywordsEn: ['personal QR', 'staff QR', 'admin scan', 'token'],
    quickHelpTh: 'เปิด QR นี้ให้แอดมินสแกนในรอบเช็กชื่อ ระบบจะไม่ใส่อีเมลหรือเบอร์โทรใน QR',
    quickHelpEn: 'Show this QR to an admin during attendance. It does not contain email or phone.',
    stepsTh: ['เปิดเมนูเช็กชื่อทีมงานหรือหน้า QR ส่วนตัวทีมงาน', 'ยืนยันตัวตนถ้ายังไม่เคยใช้เครื่องนี้', 'กดแสดง QR ของฉัน', 'ให้แอดมินสแกนจากหน้ารอบเช็กชื่อที่เปิดอยู่'],
    stepsEn: ['Open Staff Attendance or Staff Personal QR.', 'Verify identity if this device is not remembered.', 'Tap Show my QR.', 'Let an admin scan it from the active session page.'],
    tipsTh: ['QR นี้เป็นรหัสสุ่ม ไม่ใช่อีเมล เบอร์โทร หรือรหัสนักศึกษา', 'ถ้าคิดว่า QR ถูกแชร์ผิดคน ให้ยืนยันใหม่หรือขอแอดมินช่วย'],
    tipsEn: ['This QR is a random code, not email, phone, or student ID.', 'If the QR was shared incorrectly, re-verify or ask an admin for help.'],
    commonProblemsTh: [
      { problem: 'แอดมินสแกนแล้วไม่เข้า', solution: 'ตรวจว่ารอบเช็กชื่อยังเปิดอยู่ และทีมงานอยู่ในกลุ่มเป้าหมายของรอบนั้น' },
    ],
    commonProblemsEn: [
      { problem: 'Admin scan does not check me in.', solution: 'Confirm the session is active and you are in its target scope.' },
    ],
    relatedTopicIds: ['staff-attendance.personal-qr', 'admin-attendance.scan-staff-qr', 'faq.qr-difference'],
  },
  {
    topicId: 'staff-attendance.overview',
    id: 'staff-attendance.overview',
    category: 'staff-attendance',
    slug: 'overview',
    titleTh: 'เช็กชื่อทีมงานภาพรวม',
    titleEn: 'Staff Attendance Overview',
    summaryTh: 'ระบบเช็กชื่อรองรับ QR รอบเช็กชื่อ, ยืนยันอีเมล+เบอร์โทร, QR ส่วนตัว และ Manual',
    summaryEn: 'Attendance supports session QR, email+phone verification, personal QR, and manual fallback.',
    audience: ['staff', 'admin'],
    relatedRoutes: ['/staff/attendance', '/admin/staff/attendance'],
    keywordsTh: ['เช็กชื่อ', 'เช็คชื่อ', 'attendance', 'QR', 'manual', 'ทีมงานไม่มีบัญชี'],
    keywordsEn: ['attendance', 'check-in', 'QR', 'manual', 'no auth staff'],
    quickHelpTh: 'เลือกวิธีที่เร็วที่สุด: ทีมงานสแกน QR รอบเช็กชื่อเอง หรือให้แอดมินเช็กแบบ Manual/QR ส่วนตัว',
    quickHelpEn: 'Use the fastest available method: staff self-scan a session QR, or admin uses manual/personal QR check-in.',
    whenToUseTh: ['เมื่อต้องเช็กทีมงานจำนวนมากในเวลาสั้น', 'เมื่อต้องมี fallback หากกล้องหรือบัญชีเข้าสู่ระบบมีปัญหา'],
    whenToUseEn: ['When many staff need to check in quickly.', 'When you need fallbacks for camera or login issues.'],
    stepsTh: ['แอดมินสร้างรอบเช็กชื่อและเปิดใช้งาน', 'ทีมงานสแกน QR รอบเช็กชื่อด้วยมือถือของตัวเอง', 'ทีมงานไม่มีบัญชีสามารถยืนยันอีเมล+เบอร์โทรได้', 'ถ้ามีปัญหา แอดมินเช็กชื่อ Manual หรือสแกน QR ส่วนตัวทีมงาน'],
    stepsEn: ['Admin creates and activates a session.', 'Staff scan the session QR with their own phones.', 'Staff without accounts can verify by email and phone.', 'If needed, admin uses manual check-in or scans staff personal QR.'],
    fieldNotesTh: [
      { label: 'QR รอบเช็กชื่อ', description: 'ใช้ให้ทีมงานเช็กชื่อด้วยตัวเอง' },
      { label: 'QR ส่วนตัว', description: 'ใช้ให้แอดมินสแกนระบุตัวทีมงาน' },
      { label: 'Manual', description: 'ใช้เป็นทางสำรองเมื่อสแกนไม่ได้' },
    ],
    fieldNotesEn: [
      { label: 'Session QR', description: 'Used by staff to self check-in.' },
      { label: 'Personal QR', description: 'Used by admin to identify a staff member.' },
      { label: 'Manual', description: 'Fallback when scanning fails.' },
    ],
    tipsTh: ['เตรียม Manual fallback ไว้เสมอในวันงาน', 'ข้อความ error ควรบอกทีมงานว่าต้องให้แอดมินช่วยอย่างไร'],
    tipsEn: ['Always keep manual fallback ready on event day.', 'Error messages should tell staff what to do next.'],
    commonProblemsTh: [
      { problem: 'กล้องเปิดไม่ได้', solution: 'ใช้ช่องวางลิงก์/token หรือให้แอดมินเช็กแบบ Manual' },
      { problem: 'สแกนแล้วขึ้นว่าไม่อยู่ในกลุ่มเป้าหมาย', solution: 'ตรวจว่ารอบเช็กชื่อสร้างสำหรับกลุ่ม/ฝ่ายถูกต้องหรือไม่' },
    ],
    commonProblemsEn: [
      { problem: 'Camera cannot open.', solution: 'Paste the link/token or ask admin for manual check-in.' },
      { problem: 'Not in target scope.', solution: 'Confirm the session target group/role is correct.' },
    ],
    relatedTopicIds: ['staff-attendance.session-qr', 'staff-attendance.personal-qr', 'admin-attendance.manual-checkin'],
  },
  {
    topicId: 'staff-attendance.session-qr',
    id: 'staff-attendance.session-qr',
    category: 'staff-attendance',
    slug: 'session-qr',
    titleTh: 'สแกน QR รอบเช็กชื่อ',
    titleEn: 'Scan Session QR',
    summaryTh: 'ทีมงานสแกน QR ที่แอดมินแสดงเพื่อเช็กชื่อตัวเอง',
    summaryEn: 'Staff scan the QR shown by admin to check themselves in.',
    audience: ['staff'],
    relatedRoutes: ['/staff/attendance', '/staff/attendance/scan'],
    keywordsTh: ['สแกน', 'QR รอบ', 'เช็กชื่อเอง', 'หมดอายุ', 'มาสาย'],
    keywordsEn: ['scan', 'session QR', 'self check-in', 'expired', 'late'],
    quickHelpTh: 'สแกน QR รอบเช็กชื่อ ถ้าเครื่องจำตัวตนแล้วจะเช็กชื่อได้ทันทีโดยไม่กรอกอีเมลซ้ำ',
    quickHelpEn: 'Scan the session QR. If this device remembers you, check-in can finish without retyping email and phone.',
    stepsTh: ['เปิดกล้องมือถือหรือปุ่มสแกน QR ในเว็บ', 'สแกน QR รอบเช็กชื่อที่แอดมินแสดง', 'ถ้ายังไม่เคยยืนยันเครื่องนี้ ให้กรอกอีเมลและเบอร์โทร', 'ดูผลลัพธ์ว่าเช็กชื่อสำเร็จ มาสาย หรือเช็กไปแล้ว'],
    stepsEn: ['Open your phone camera or the in-app scanner.', 'Scan the session QR shown by admin.', 'If this device is not remembered, enter email and phone.', 'Read whether you are present, late, or already checked.'],
    tipsTh: ['ถ้า QR หมดอายุ ให้ขอ QR ใหม่จากแอดมิน', 'อย่าใช้ QR ส่วนตัวแทน QR รอบเช็กชื่อ'],
    tipsEn: ['If the QR expired, ask admin for a new one.', 'Do not use personal QR as a session QR.'],
    commonProblemsTh: [
      { problem: 'QR หมดอายุ', solution: 'ให้แอดมินสร้าง QR ใหม่หรือเปิดรอบใหม่' },
      { problem: 'เช็กชื่อแล้วขึ้นซ้ำ', solution: 'ระบบกันรายการซ้ำไว้แล้ว ไม่ต้องกดซ้ำ' },
    ],
    commonProblemsEn: [
      { problem: 'QR expired.', solution: 'Ask admin to regenerate the QR or create a new session.' },
      { problem: 'Already checked.', solution: 'The system prevents duplicates; no extra action is needed.' },
    ],
    relatedTopicIds: ['staff-attendance.camera-scan', 'staff-attendance.personal-qr', 'faq.qr-difference'],
  },
  {
    topicId: 'staff-attendance.camera-scan',
    id: 'staff-attendance.camera-scan',
    category: 'staff-attendance',
    slug: 'camera-scan',
    titleTh: 'เปิดกล้องสแกน QR ในเว็บ',
    titleEn: 'Use In-Browser QR Camera Scanner',
    summaryTh: 'เปิดกล้องหลังในเว็บเพื่อสแกน QR รอบเช็กชื่อ พร้อมช่องวาง token สำรอง',
    summaryEn: 'Open the rear camera in the web app to scan a session QR, with paste-token fallback.',
    audience: ['staff', 'admin'],
    relatedRoutes: ['/staff/attendance'],
    keywordsTh: ['กล้อง', 'สแกน', 'อนุญาตกล้อง', 'camera', 'fallback', 'token'],
    keywordsEn: ['camera', 'scanner', 'permission', 'fallback', 'paste token'],
    quickHelpTh: 'กดเปิดกล้อง อนุญาตการใช้กล้อง แล้วเล็งไปที่ QR หากกล้องใช้ไม่ได้ให้วางลิงก์หรือ token แทน',
    quickHelpEn: 'Tap open camera, allow permission, and point at the QR. If camera fails, paste the link or token.',
    stepsTh: ['กดเปิดกล้อง', 'อนุญาตให้ browser ใช้กล้อง', 'เล็งกล้องไปที่ QR จนระบบอ่านได้', 'ถ้ากล้องไม่เปิด ใช้ช่องวางลิงก์หรือ token'],
    stepsEn: ['Tap Open camera.', 'Allow browser camera access.', 'Point the camera at the QR until it reads.', 'If camera fails, paste the link or token.'],
    tipsTh: ['ใช้กล้องหลังจะอ่าน QR ได้ง่ายกว่า', 'บน iOS/Android ต้องเปิดผ่าน HTTPS หรือโดเมนที่ browser อนุญาต'],
    tipsEn: ['Rear camera scans more reliably.', 'On iOS/Android, camera access requires HTTPS or an allowed browser context.'],
    commonProblemsTh: [
      { problem: 'เปิดกล้องไม่ได้', solution: 'กดอนุญาตกล้องใน browser หรือใช้ช่องวาง token สำรอง' },
    ],
    commonProblemsEn: [
      { problem: 'Camera cannot open.', solution: 'Allow camera access in the browser, or paste the token as fallback.' },
    ],
    relatedTopicIds: ['staff-attendance.session-qr', 'admin-attendance.scan-staff-qr'],
  },
  {
    topicId: 'staff-attendance.personal-qr',
    id: 'staff-attendance.personal-qr',
    category: 'staff-attendance',
    slug: 'personal-qr',
    titleTh: 'QR ส่วนตัวให้แอดมินสแกน',
    titleEn: 'Personal QR for Admin-Assisted Check-In',
    summaryTh: 'ทีมงานเปิด QR ส่วนตัว แล้วแอดมินสแกนในรอบเช็กชื่อที่เลือก',
    summaryEn: 'Staff show their personal QR, and an admin scans it inside the selected session.',
    audience: ['staff', 'admin'],
    relatedRoutes: ['/staff/attendance', '/staff/profile/qr', '/admin/staff/attendance'],
    keywordsTh: ['QR ส่วนตัว', 'แอดมินสแกน', 'เช็กชื่อแทน', 'ไม่มีบัญชี'],
    keywordsEn: ['personal QR', 'admin scan', 'assisted check-in', 'no account'],
    quickHelpTh: 'ใช้เมื่อแอดมินเป็นคนเช็กชื่อให้ ทีมงานแสดง QR ส่วนตัว แอดมินสแกนจากรอบเช็กชื่อที่เปิดอยู่',
    quickHelpEn: 'Use when admin checks staff in. Staff show personal QR; admin scans it from the active session.',
    stepsTh: ['ทีมงานเปิดเมนูเช็กชื่อทีมงาน', 'กดแสดง QR ของฉัน', 'แอดมินเปิดรอบเช็กชื่อและสแกน QR ส่วนตัว', 'ระบบบันทึกสถานะในรอบนั้น'],
    stepsEn: ['Staff open Staff Attendance.', 'Tap Show my QR.', 'Admin opens a session and scans the personal QR.', 'The system records attendance for that session.'],
    tipsTh: ['QR ส่วนตัวระบุตัวทีมงานเท่านั้น ไม่ใช่ QR รอบเช็กชื่อ', 'ถ้าสแกนไม่ได้ ใช้ Manual check-in แทน'],
    tipsEn: ['Personal QR only identifies staff; it is not a session QR.', 'If scanning fails, use manual check-in.'],
    commonProblemsTh: [
      { problem: 'ใช้ QR ผิดประเภท', solution: 'QR รอบเช็กชื่อใช้ให้ทีมงานสแกนเอง ส่วน QR ส่วนตัวใช้ให้แอดมินสแกน' },
    ],
    commonProblemsEn: [
      { problem: 'Wrong QR type.', solution: 'Session QR is for staff self check-in; personal QR is for admin scan.' },
    ],
    relatedTopicIds: ['admin-attendance.scan-staff-qr', 'faq.qr-difference', 'staff.personal-qr'],
  },
  {
    topicId: 'admin.login',
    id: 'admin.login',
    category: 'admin',
    slug: 'login',
    titleTh: 'เข้าสู่ระบบแอดมิน',
    titleEn: 'Admin Sign In',
    summaryTh: 'แอดมินต้องใช้บัญชีที่มีสิทธิ์ผู้ดูแลระบบ ทีมงานทั่วไปเข้าเมนูแอดมินไม่ได้',
    summaryEn: 'Admins need an account with admin access. Regular staff cannot enter admin-only tools.',
    audience: ['admin'],
    relatedRoutes: ['/login', '/admin'],
    keywordsTh: ['แอดมิน', 'ผู้ดูแลระบบ', 'เข้าสู่ระบบ', 'ไม่มีสิทธิ์'],
    keywordsEn: ['admin', 'login', 'access denied', 'permission'],
    quickHelpTh: 'เข้าสู่ระบบด้วยบัญชีแอดมิน หากเป็นบัญชีทีมงาน ระบบจะพาไป Staff Mode แทน',
    quickHelpEn: 'Sign in with an admin account. Staff accounts are routed to Staff Mode instead.',
    stepsTh: ['เปิด /login หรือ /admin', 'กรอกอีเมลและรหัสผ่าน', 'ระบบตรวจสิทธิ์แอดมินก่อน แล้วจึงตรวจสิทธิ์ทีมงาน', 'ถ้าเป็นแอดมินจะไปหน้า Dashboard'],
    stepsEn: ['Open /login or /admin.', 'Enter email and password.', 'The app checks admin access first, then staff access.', 'Admins go to the dashboard.'],
    tipsTh: ['อย่าแชร์บัญชีแอดมิน', 'ถ้าเห็นข้อความไม่มีสิทธิ์ผู้ดูแล ให้ตรวจในตาราง admins หรือสิทธิ์ RPC'],
    tipsEn: ['Do not share admin accounts.', 'If admin access is denied, check the admins table or admin RPC permissions.'],
    commonProblemsTh: [
      { problem: 'บัญชีทีมงานเข้า Dashboard ไม่ได้', solution: 'ถูกต้องแล้ว ทีมงานไม่ควรเข้าเมนูแอดมิน ให้ใช้ Staff Mode' },
    ],
    commonProblemsEn: [
      { problem: 'Staff account cannot enter dashboard.', solution: 'That is expected. Staff should use Staff Mode.' },
    ],
    relatedTopicIds: ['staff.login', 'admin.dashboard'],
  },
  {
    topicId: 'admin.dashboard',
    id: 'admin.dashboard',
    category: 'admin',
    slug: 'dashboard',
    titleTh: 'Dashboard ผู้ดูแลระบบ',
    titleEn: 'Admin Dashboard',
    summaryTh: 'ดูภาพรวมจำนวนผู้เข้าร่วม คำขอแก้ไข ข้อมูลสุขภาพ และ Export',
    summaryEn: 'Review participant totals, pending edit requests, health summaries, and exports.',
    audience: ['admin'],
    relatedRoutes: ['/admin/dashboard'],
    keywordsTh: ['dashboard', 'แดชบอร์ด', 'สรุป', 'export', 'คำขอ'],
    keywordsEn: ['dashboard', 'summary', 'export', 'requests'],
    quickHelpTh: 'ใช้ Dashboard เพื่อดูสถานะรวมก่อนลงรายละเอียดในรายชื่อ กลุ่ม หรือ Data Health',
    quickHelpEn: 'Use Dashboard for overall status before drilling into participants, groups, or Data Health.',
    stepsTh: ['เข้าสู่ระบบแอดมิน', 'เปิด Dashboard', 'ดูการ์ดสรุปและคำขอที่รออนุมัติ', 'ใช้ค้นหา/ตัวกรองเมื่อจัดการรายชื่อ', 'Export เมื่อต้องส่งข้อมูลให้ทีมที่เกี่ยวข้อง'],
    stepsEn: ['Sign in as admin.', 'Open Dashboard.', 'Review summary cards and pending requests.', 'Use search/filter for participant operations.', 'Export when data needs to be shared internally.'],
    tipsTh: ['ถ้า Dashboard ดูผิดปกติ ให้ไป Data Health ก่อนแก้ข้อมูลจริง'],
    tipsEn: ['If dashboard data looks unusual, check Data Health before editing records.'],
    commonProblemsTh: [
      { problem: 'ข้อมูลใน Dashboard ไม่ขึ้น', solution: 'ตรวจ Supabase connection, RPC ที่เกี่ยวข้อง และสิทธิ์แอดมิน' },
    ],
    commonProblemsEn: [
      { problem: 'Dashboard data does not load.', solution: 'Check Supabase connection, related RPCs, and admin access.' },
    ],
    relatedTopicIds: ['admin.participants', 'admin.groups', 'admin-attendance.create-session'],
  },
  {
    topicId: 'admin.participants',
    id: 'admin.participants',
    category: 'admin',
    slug: 'participants',
    titleTh: 'จัดการรายชื่อผู้เข้าร่วม',
    titleEn: 'Manage Participants',
    summaryTh: 'ค้นหา กรอง แก้ไข อนุมัติคำขอ และ Export ข้อมูลผู้เข้าร่วม',
    summaryEn: 'Search, filter, edit, approve requests, and export participant data.',
    audience: ['admin'],
    relatedRoutes: ['/admin/dashboard', '/admin/requests'],
    keywordsTh: ['รายชื่อ', 'ผู้เข้าร่วม', 'อนุมัติ', 'คำขอ', 'export'],
    keywordsEn: ['participants', 'profiles', 'approve', 'requests', 'export'],
    quickHelpTh: 'ใช้ค้นหาและกรองรายชื่อก่อนแก้ไขข้อมูลจริง ระวังข้อมูลสุขภาพและข้อมูลติดต่อ',
    quickHelpEn: 'Search and filter before editing records. Treat contact and health data carefully.',
    stepsTh: ['เปิด Dashboard หรือหน้าคำขอ', 'ค้นหาด้วยชื่อ สาขา กลุ่ม หรือสถานะสุขภาพ', 'เปิดรายการที่ต้องการดู', 'แก้ไขเฉพาะข้อมูลที่จำเป็น', 'อนุมัติ/ปฏิเสธคำขอพร้อมตรวจข้อมูลเก่า-ใหม่'],
    stepsEn: ['Open Dashboard or Requests.', 'Search by name, major, group, or health status.', 'Open the target profile.', 'Edit only necessary fields.', 'Approve/reject requests after comparing old and new values.'],
    tipsTh: ['อย่า export ข้อมูลสุขภาพให้บุคคลที่ไม่มีสิทธิ์', 'ถ้าแก้หลายรายการ ให้บันทึก change log ไว้เสมอ'],
    tipsEn: ['Do not export health data to unauthorized people.', 'For bulk changes, keep audit/change logs.'],
    commonProblemsTh: [
      { problem: 'คำขอแสดงเหมือนแก้หลายช่องทั้งที่แก้ช่องเดียว', solution: 'ตรวจ UI diff และแสดงเฉพาะ field ที่ค่าเปลี่ยนจริง' },
    ],
    commonProblemsEn: [
      { problem: 'Request diff looks like many fields changed.', solution: 'Show only fields where old and new values are actually different.' },
    ],
    relatedTopicIds: ['participant.edit-info', 'admin.dashboard'],
  },
  {
    topicId: 'admin.groups',
    id: 'admin.groups',
    category: 'admin',
    slug: 'groups',
    titleTh: 'จัดกลุ่มผู้เข้าร่วม',
    titleEn: 'Group Assignment',
    summaryTh: 'จัด main group/subgroup และตรวจความถูกต้องของการมอบหมายกลุ่ม',
    summaryEn: 'Manage main group/subgroup assignments and validate group data.',
    audience: ['admin'],
    relatedRoutes: ['/admin/groups'],
    keywordsTh: ['จัดกลุ่ม', 'สี', 'กลุ่มย่อย', 'main group', 'subgroup'],
    keywordsEn: ['groups', 'main group', 'subgroup', 'assignment'],
    quickHelpTh: 'ใช้หน้านี้ตรวจว่าผู้เข้าร่วมถูกจัดเข้ากลุ่มหลักและกลุ่มย่อยถูกต้อง',
    quickHelpEn: 'Use this page to confirm participants are assigned to the correct main group and subgroup.',
    stepsTh: ['เปิดหน้าจัดกลุ่ม', 'ตรวจจำนวนแต่ละสีและกลุ่มย่อย', 'ค้นหาคนที่ต้องการปรับ', 'บันทึกและตรวจ Data Health ถ้ามีความผิดปกติ'],
    stepsEn: ['Open Groups.', 'Check counts per color/subgroup.', 'Search the person to adjust.', 'Save and check Data Health if something looks wrong.'],
    tipsTh: ['ใช้ชื่อกลุ่ม/สีตามตัวเลือกมาตรฐานเท่านั้นเพื่อลด schema drift'],
    tipsEn: ['Use only standard group/color values to avoid schema drift.'],
    commonProblemsTh: [
      { problem: 'กลุ่มไม่ขึ้นในหน้าสาธารณะ', solution: 'ตรวจว่า public view/search RPC join group_assignments ถูกต้อง' },
    ],
    commonProblemsEn: [
      { problem: 'Group does not show publicly.', solution: 'Check the public view/search RPC joins group assignments safely.' },
    ],
    relatedTopicIds: ['participant.my-group', 'admin.dashboard'],
  },
  {
    topicId: 'admin-attendance.create-session',
    id: 'admin-attendance.create-session',
    category: 'admin-attendance',
    slug: 'create-session',
    titleTh: 'สร้างรอบเช็กชื่อทีมงาน',
    titleEn: 'Create Attendance Session',
    summaryTh: 'กำหนดชื่อ เวลาเริ่ม เวลาปิด สายหลัง กลุ่มเป้าหมาย และสถานะของรอบเช็กชื่อ',
    summaryEn: 'Set title, start/end time, late threshold, target scope, and status for an attendance session.',
    audience: ['admin'],
    relatedRoutes: ['/admin/staff/attendance'],
    keywordsTh: ['สร้างรอบ', 'เวลาเริ่ม', 'เวลาปิด', 'สายหลัง', 'กลุ่มเป้าหมาย', 'เวลาไทย'],
    keywordsEn: ['create session', 'starts at', 'ends at', 'late after', 'target', 'Bangkok time'],
    quickHelpTh: 'กรอกเวลาตามเวลาไทยในเครื่องของคุณ ไม่ต้องบวกหรือลบ 7 ชั่วโมงเอง',
    quickHelpEn: 'Enter Thailand local time from your device. Do not manually add or subtract 7 hours.',
    whenToUseTh: ['ก่อนเริ่มกิจกรรมหรือแต่ละช่วงงาน', 'เมื่ออยากเช็กเฉพาะสี กลุ่มย่อย ฝ่าย หรือทีมฉุกเฉิน'],
    whenToUseEn: ['Before an activity or shift begins.', 'When checking only a color, subgroup, role, or emergency staff.'],
    stepsTh: ['กดสร้างรอบเช็กชื่อ', 'ตั้งชื่อรอบให้สั้นและเข้าใจง่าย', 'เลือกประเภทและกลุ่มเป้าหมาย', 'กรอกเวลาเริ่ม เวลาปิด และสายหลังตามเวลาไทย', 'ตั้งสถานะเป็นเปิดใช้งานเมื่อต้องการให้ QR ใช้ได้'],
    stepsEn: ['Click Create session.', 'Use a short clear title.', 'Choose type and target scope.', 'Enter start/end/late-after using Thailand time.', 'Set status to Active when the QR should work.'],
    fieldNotesTh: [
      { label: 'เวลาเริ่ม', description: 'ก่อนเวลานี้ทีมงานยังเช็กชื่อไม่ได้' },
      { label: 'เวลาปิด', description: 'หลังเวลานี้ QR จะไม่รับเช็กชื่อ' },
      { label: 'สายหลัง', description: 'เช็กหลังเวลานี้จะถูกบันทึกเป็นมาสาย' },
      { label: 'กลุ่มเป้าหมาย', description: 'กำหนดว่าใครมีสิทธิ์เช็กชื่อในรอบนี้' },
      { label: 'สถานะ', description: 'Active ใช้งานได้ ส่วน draft/closed ใช้เช็กชื่อไม่ได้' },
    ],
    fieldNotesEn: [
      { label: 'Starts', description: 'Staff cannot check in before this time.' },
      { label: 'Ends', description: 'The QR stops accepting check-ins after this time.' },
      { label: 'Late after', description: 'Check-ins after this time are recorded as late.' },
      { label: 'Target scope', description: 'Controls who is allowed to check in.' },
      { label: 'Status', description: 'Active works; draft/closed does not accept check-ins.' },
    ],
    tipsTh: ['ใช้ชื่อรอบเช่น “เช็กชื่อเช้าวันกิจกรรม” เพื่อให้ทีมงานไม่สับสน', 'ถ้ารอบแสดงเวลาผิดวัน ให้ตรวจ timezone ก่อนเปิดใช้งานจริง'],
    tipsEn: ['Use clear titles like “Morning event check-in”.', 'If the displayed time is wrong, verify timezone before using it live.'],
    commonProblemsTh: [
      { problem: 'เวลาเลื่อนไปอีกวัน', solution: 'อย่าเติม Z เอง ใช้ field datetime-local และ helper แปลงเป็น ISO จาก local time' },
      { problem: 'ทีมงานเช็กชื่อไม่ได้', solution: 'ตรวจสถานะ Active เวลาเริ่ม/ปิด และกลุ่มเป้าหมาย' },
    ],
    commonProblemsEn: [
      { problem: 'Time shifts to the next day.', solution: 'Do not append Z. Use datetime-local and convert local time correctly.' },
      { problem: 'Staff cannot check in.', solution: 'Check Active status, start/end time, and target scope.' },
    ],
    relatedTopicIds: ['admin-attendance.late-after', 'admin-attendance.session-qr', 'admin-attendance.manual-checkin'],
  },
  {
    topicId: 'admin-attendance.late-after',
    id: 'admin-attendance.late-after',
    category: 'admin-attendance',
    slug: 'late-after',
    titleTh: 'ตั้งค่าเวลานับว่าสาย',
    titleEn: 'Late After Time',
    summaryTh: 'กำหนดเวลาที่เช็กหลังจากนั้นแล้วจะถูกบันทึกเป็นสถานะมาสาย',
    summaryEn: 'Set the time after which check-ins are recorded as late.',
    audience: ['admin'],
    relatedRoutes: ['/admin/staff/attendance'],
    keywordsTh: ['สายหลัง', 'มาสาย', 'late after', 'เวลาไทย'],
    keywordsEn: ['late after', 'late', 'Bangkok time'],
    quickHelpTh: 'ตัวอย่าง: รอบเริ่ม 08:00 สายหลัง 08:15 คนเช็กหลัง 08:15 จะเป็น “มาสาย”',
    quickHelpEn: 'Example: session starts 08:00, late after 08:15. Check-ins after 08:15 are marked Late.',
    stepsTh: ['กำหนดเวลาเริ่มรอบ', 'ตั้งเวลาสายหลังเป็นเวลาผ่อนผัน', 'ปล่อยว่างได้ถ้าไม่ต้องแยกสถานะมาสาย'],
    stepsEn: ['Set the session start time.', 'Set late-after as the grace period.', 'Leave empty if you do not need late status.'],
    tipsTh: ['เวลาที่กรอกคือเวลาไทยตามเครื่องของผู้ใช้'],
    tipsEn: ['The entered time is Thailand local time from the user device.'],
    commonProblemsTh: [
      { problem: 'ทุกคนกลายเป็นมาสาย', solution: 'ตรวจว่าสายหลังไม่ได้ตั้งไว้ก่อนเวลาเริ่มหรือผิดวัน' },
    ],
    commonProblemsEn: [
      { problem: 'Everyone becomes late.', solution: 'Check that late-after is not before the start time or on the wrong day.' },
    ],
    relatedTopicIds: ['admin-attendance.create-session', 'faq.attendance-time-error'],
  },
  {
    topicId: 'admin-attendance.session-qr',
    id: 'admin-attendance.session-qr',
    category: 'admin-attendance',
    slug: 'session-qr',
    titleTh: 'QR รอบเช็กชื่อ',
    titleEn: 'Attendance Session QR',
    summaryTh: 'แสดง QR ให้ทีมงานสแกนด้วยมือถือของตัวเองเพื่อเช็กชื่อ',
    summaryEn: 'Show a QR that staff scan with their own phones to check in.',
    audience: ['admin'],
    relatedRoutes: ['/admin/staff/attendance'],
    keywordsTh: ['QR รอบ', 'แสดง QR', 'คัดลอกลิงก์', 'สร้าง QR ใหม่', 'ปิดรอบ'],
    keywordsEn: ['session QR', 'show QR', 'copy link', 'regenerate QR', 'close session'],
    quickHelpTh: 'ให้ทีมงานสแกน QR นี้ด้วยมือถือของตัวเอง ถ้า QR หลุดหรือหมดอายุให้สร้าง QR ใหม่',
    quickHelpEn: 'Let staff scan this QR with their own phones. Regenerate it if it leaks or expires.',
    stepsTh: ['เปิดรายละเอียดรอบเช็กชื่อ', 'แสดง QR บนหน้าจอให้ทีมงานสแกน', 'ใช้คัดลอกลิงก์เมื่อส่งในช่องทางทีมงาน', 'สร้าง QR ใหม่ถ้าต้องยกเลิก QR เก่า', 'ปิดรอบเมื่อไม่รับเช็กชื่อแล้ว'],
    stepsEn: ['Open the session detail.', 'Show the QR on screen.', 'Copy the link if sharing with staff.', 'Regenerate QR to invalidate the old one.', 'Close the session when check-in is finished.'],
    tipsTh: ['อย่าแชร์ QR เกินกลุ่มเป้าหมาย', 'QR รอบเช็กชื่อต่างจาก QR ส่วนตัวทีมงาน'],
    tipsEn: ['Do not share the QR outside the target scope.', 'Session QR is different from staff personal QR.'],
    commonProblemsTh: [
      { problem: 'ทีมงานสแกนแล้วขึ้น QR หมดอายุ', solution: 'กดสร้าง QR ใหม่หรือขยายเวลาหมดอายุถ้าตั้งไว้' },
    ],
    commonProblemsEn: [
      { problem: 'Staff sees QR expired.', solution: 'Regenerate QR or adjust expiry if configured.' },
    ],
    relatedTopicIds: ['staff-attendance.session-qr', 'admin-attendance.create-session', 'faq.qr-difference'],
  },
  {
    topicId: 'admin-attendance.manual-checkin',
    id: 'admin-attendance.manual-checkin',
    category: 'admin-attendance',
    slug: 'manual-checkin',
    titleTh: 'เช็กชื่อแบบ Manual',
    titleEn: 'Manual Check-In',
    summaryTh: 'แอดมินค้นหาทีมงานและกดสถานะ มาแล้ว มาสาย ขาด หรือขออนุญาต',
    summaryEn: 'Admins search staff and mark Present, Late, Absent, or Excused.',
    audience: ['admin'],
    relatedRoutes: ['/admin/staff/attendance'],
    keywordsTh: ['manual', 'เช็กชื่อแทน', 'มาแล้ว', 'มาสาย', 'ขาด', 'ลา', 'หมายเหตุ'],
    keywordsEn: ['manual', 'present', 'late', 'absent', 'excused', 'note'],
    quickHelpTh: 'ใช้เป็น fallback เมื่อตัวทีมงานสแกน QR ไม่ได้หรือไม่มีมือถือพร้อมใช้',
    quickHelpEn: 'Use this fallback when staff cannot scan QR or do not have their phone ready.',
    stepsTh: ['เปิดรอบเช็กชื่อ', 'ค้นหาชื่อทีมงาน', 'เลือกสถานะที่ถูกต้อง', 'เพิ่มหมายเหตุถ้าจำเป็น', 'ตรวจว่ารายการอัปเดตใน summary แล้ว'],
    stepsEn: ['Open the session.', 'Search for staff.', 'Choose the correct status.', 'Add a note if needed.', 'Confirm the summary updates.'],
    tipsTh: ['ใช้หมายเหตุสั้น ๆ เช่น “ลงทะเบียนกับหัวหน้าทีม”', 'Manual ควรใช้เฉพาะเมื่อจำเป็นเพื่อให้ audit ชัดเจน'],
    tipsEn: ['Use short notes like “checked in by team lead”.', 'Use manual only when needed so the audit trail stays clear.'],
    commonProblemsTh: [
      { problem: 'หา staff ไม่เจอ', solution: 'ล้าง filter สถานะ หรือค้นด้วยชื่อเล่น/อีเมล/หน้าที่' },
    ],
    commonProblemsEn: [
      { problem: 'Cannot find a staff member.', solution: 'Clear status filters or search by nickname, email, or role.' },
    ],
    relatedTopicIds: ['admin-attendance.scan-staff-qr', 'admin-attendance.export'],
  },
  {
    topicId: 'admin-attendance.scan-staff-qr',
    id: 'admin-attendance.scan-staff-qr',
    category: 'admin-attendance',
    slug: 'scan-staff-qr',
    titleTh: 'สแกน QR ส่วนตัวทีมงาน',
    titleEn: 'Scan Staff Personal QR',
    summaryTh: 'แอดมินเปิด scanner ในรอบเช็กชื่อ แล้วสแกน QR ส่วนตัวของทีมงาน',
    summaryEn: 'Admin opens the scanner inside a session and scans a staff personal QR.',
    audience: ['admin'],
    relatedRoutes: ['/admin/staff/attendance'],
    keywordsTh: ['สแกน QR ทีมงาน', 'QR ส่วนตัว', 'แอดมินสแกน', 'กล้อง', 'token'],
    keywordsEn: ['scan staff QR', 'personal QR', 'admin scan', 'camera', 'token'],
    quickHelpTh: 'กดสแกน QR ทีมงาน เปิดกล้อง แล้วสแกน QR ส่วนตัว ถ้ากล้องไม่ได้ให้วาง token แทน',
    quickHelpEn: 'Click Scan Staff QR, open camera, and scan the personal QR. If camera fails, paste the token.',
    stepsTh: ['เปิดรอบเช็กชื่อที่ Active', 'เปิดเครื่องมือสแกน QR ส่วนตัวทีมงาน', 'กดเปิดกล้องและอนุญาตการใช้กล้อง', 'สแกน QR ที่ทีมงานแสดง', 'ถ้าสแกนไม่ได้ วาง token หรือข้อความจาก QR'],
    stepsEn: ['Open an Active attendance session.', 'Open Scan staff personal QR.', 'Tap Open camera and allow camera access.', 'Scan the QR shown by staff.', 'If scanning fails, paste the token/QR text.'],
    tipsTh: ['ระบบจะบันทึก method เป็น admin_scan_staff_qr เพื่อ audit', 'ถ้าทีมงานไม่อยู่ในกลุ่มเป้าหมาย ระบบจะปฏิเสธ'],
    tipsEn: ['The system records method as admin_scan_staff_qr for audit.', 'If staff is outside target scope, the app rejects the check-in.'],
    commonProblemsTh: [
      { problem: 'QR ไม่ถูกต้อง', solution: 'ตรวจว่าเป็น QR ส่วนตัวทีมงาน ไม่ใช่ QR รอบเช็กชื่อ' },
      { problem: 'ไม่อยู่ในกลุ่มเป้าหมาย', solution: 'ตรวจ target scope ของรอบเช็กชื่อ หรือใช้รอบที่ถูกต้อง' },
    ],
    commonProblemsEn: [
      { problem: 'Invalid QR.', solution: 'Confirm this is staff personal QR, not session QR.' },
      { problem: 'Not in target scope.', solution: 'Check the session target scope or use the correct session.' },
    ],
    relatedTopicIds: ['staff-attendance.personal-qr', 'admin-attendance.manual-checkin', 'faq.qr-difference'],
  },
  {
    topicId: 'admin-attendance.export',
    id: 'admin-attendance.export',
    category: 'admin-attendance',
    slug: 'export',
    titleTh: 'Export รายงานเช็กชื่อ',
    titleEn: 'Export Attendance Report',
    summaryTh: 'ดาวน์โหลด CSV พร้อมชื่อทีมงาน กลุ่ม สถานะ วิธีเช็ก เวลา และหมายเหตุ',
    summaryEn: 'Download CSV with staff, group, status, method, checked time, and note.',
    audience: ['admin'],
    relatedRoutes: ['/admin/staff/attendance'],
    keywordsTh: ['export', 'CSV', 'รายงาน', 'checked_by', 'method'],
    keywordsEn: ['export', 'CSV', 'report', 'checked_by', 'method'],
    quickHelpTh: 'กด CSV ในหน้ารอบเช็กชื่อเพื่อดาวน์โหลดรายงาน ใช้ภายในทีมเท่านั้น',
    quickHelpEn: 'Click CSV on the session page to download the report for internal use only.',
    stepsTh: ['เปิดรายละเอียดรอบเช็กชื่อ', 'ตรวจ summary และสถานะในรายการ', 'กด CSV', 'เก็บไฟล์ในพื้นที่ที่ทีมมีสิทธิ์เข้าถึงเท่านั้น'],
    stepsEn: ['Open the session detail.', 'Review summary and row statuses.', 'Click CSV.', 'Store the file only where authorized staff can access it.'],
    fieldNotesTh: [
      { label: 'method', description: 'บอกวิธีเช็กชื่อ เช่น session_qr, verified_qr, manual, admin_scan_staff_qr' },
      { label: 'checked_by', description: 'ระบุแอดมินเมื่อเป็นการเช็กแบบ Manual หรือสแกน QR ส่วนตัว' },
    ],
    fieldNotesEn: [
      { label: 'method', description: 'Shows the check-in method, such as session_qr, verified_qr, manual, or admin_scan_staff_qr.' },
      { label: 'checked_by', description: 'Identifies the admin for manual or personal QR scan methods.' },
    ],
    tipsTh: ['หลีกเลี่ยงการส่งไฟล์ผ่านช่องทางสาธารณะ'],
    tipsEn: ['Avoid sharing exports through public channels.'],
    commonProblemsTh: [
      { problem: 'ไฟล์เปิดแล้วภาษาไทยเพี้ยน', solution: 'เปิดด้วยโปรแกรมที่รองรับ UTF-8 หรือ import CSV ด้วย encoding UTF-8' },
    ],
    commonProblemsEn: [
      { problem: 'Thai text looks broken.', solution: 'Open/import the CSV using UTF-8 encoding.' },
    ],
    relatedTopicIds: ['admin-attendance.manual-checkin', 'admin.dashboard'],
  },
  {
    topicId: 'documents.overview',
    id: 'documents.overview',
    category: 'documents',
    slug: 'overview',
    titleTh: 'Document Center ภาพรวม',
    titleEn: 'Document Center Overview',
    summaryTh: 'จัดข้อมูลโครงการ เทมเพลต DOCX สร้างเอกสาร และดูประวัติไฟล์ที่สร้างแล้ว',
    summaryEn: 'Manage project data, DOCX templates, generated documents, and history.',
    audience: ['admin'],
    relatedRoutes: ['/admin/documents'],
    keywordsTh: ['เอกสาร', 'document center', 'โครงการ', 'template', 'docx'],
    keywordsEn: ['documents', 'document center', 'project profile', 'template', 'docx'],
    quickHelpTh: 'เริ่มจากตั้งค่าข้อมูลโครงการ จากนั้นอัปโหลด template แล้วไปหน้าสร้างเอกสาร',
    quickHelpEn: 'Start by setting project data, upload templates, then generate documents.',
    stepsTh: ['เปิดศูนย์เอกสาร', 'ตรวจตั้งค่าโครงการ', 'อัปโหลดหรือเลือก template ที่ active', 'สร้างเอกสารและตรวจ preview', 'ดาวน์โหลดจากประวัติเมื่อสร้างสำเร็จ'],
    stepsEn: ['Open Document Center.', 'Review project settings.', 'Upload or select an active template.', 'Generate and preview the document.', 'Download from history after generation.'],
    tipsTh: ['ข้อมูลโครงการควรถูกบันทึกผ่าน RPC เพื่อให้ budget/schedule/venue atomically', 'อย่าเผยแพร่ signed URL ถ้าไม่จำเป็น'],
    tipsEn: ['Project data should save through RPC for atomic budget/schedule/venue updates.', 'Do not expose signed URLs unless necessary.'],
    commonProblemsTh: [
      { problem: 'สร้างเอกสารแล้ว field หาย', solution: 'ตรวจ placeholder ใน template และข้อมูลที่กรอกใน Project Settings' },
    ],
    commonProblemsEn: [
      { problem: 'Generated fields are missing.', solution: 'Check template placeholders and Project Settings data.' },
    ],
    relatedTopicIds: ['documents.templates', 'documents.generate'],
  },
  {
    topicId: 'documents.templates',
    id: 'documents.templates',
    category: 'documents',
    slug: 'templates',
    titleTh: 'อัปโหลด Template',
    titleEn: 'Upload DOCX Template',
    summaryTh: 'อัปโหลด DOCX ที่ใช้ placeholder มาตรฐาน แล้วตรวจ placeholder ที่ระบบพบ',
    summaryEn: 'Upload DOCX templates with standard placeholders and review detected placeholders.',
    audience: ['admin'],
    relatedRoutes: ['/admin/documents/templates'],
    keywordsTh: ['template', 'เทมเพลต', 'docx', 'placeholder', 'อัปโหลด'],
    keywordsEn: ['template', 'docx', 'placeholder', 'upload'],
    quickHelpTh: 'ใช้ไฟล์ .docx เท่านั้น และใช้ placeholder ตัวพิมพ์เล็ก เช่น {project_name}',
    quickHelpEn: 'Use .docx files only, with lowercase placeholders such as {project_name}.',
    stepsTh: ['เปิดหน้า Templates', 'เลือกไฟล์ .docx', 'ตรวจ placeholder ที่ระบบอ่านเจอ', 'แก้ placeholder ที่เป็นตัวใหญ่หรือ syntax ผิด', 'ตั้ง active เฉพาะ template ที่พร้อมใช้'],
    stepsEn: ['Open Templates.', 'Choose a .docx file.', 'Review detected placeholders.', 'Fix uppercase or invalid syntax placeholders.', 'Set active only for ready templates.'],
    fieldNotesTh: [
      { label: 'placeholder', description: 'ข้อความใน template เช่น {project_name} ที่ระบบจะแทนค่าจริง' },
      { label: 'active', description: 'template ที่พร้อมเลือกในหน้าสร้างเอกสาร' },
    ],
    fieldNotesEn: [
      { label: 'placeholder', description: 'Template tokens such as {project_name} that are replaced by real values.' },
      { label: 'active', description: 'Templates available for document generation.' },
    ],
    tipsTh: ['ถ้า DB insert ล้มเหลว ระบบควรลบไฟล์ Storage ที่อัปโหลดค้างไว้'],
    tipsEn: ['If DB insert fails, uploaded Storage files should be rolled back.'],
    commonProblemsTh: [
      { problem: 'อัปโหลดไฟล์ไม่ได้', solution: 'ตรวจว่าเป็น .docx และ bucket document-templates เป็น private พร้อม policy แอดมิน' },
    ],
    commonProblemsEn: [
      { problem: 'Upload fails.', solution: 'Confirm the file is .docx and the private template bucket allows admin upload.' },
    ],
    relatedTopicIds: ['documents.overview', 'documents.generate'],
  },
  {
    topicId: 'documents.generate',
    id: 'documents.generate',
    category: 'documents',
    slug: 'generate',
    titleTh: 'สร้างเอกสาร',
    titleEn: 'Generate Document',
    summaryTh: 'เลือก template ตรวจข้อมูลที่ขาด ดู preview และสร้างไฟล์ DOCX',
    summaryEn: 'Choose a template, review missing fields, preview, and generate DOCX.',
    audience: ['admin'],
    relatedRoutes: ['/admin/documents/generate', '/admin/documents/history'],
    keywordsTh: ['generate', 'สร้างเอกสาร', 'preview', 'download', 'missing fields'],
    keywordsEn: ['generate', 'preview', 'download', 'missing fields'],
    quickHelpTh: 'เลือกประเภทเอกสารและ template ก่อนสร้าง หากมีข้อมูลที่ขาดให้กลับไปตั้งค่าโครงการ',
    quickHelpEn: 'Choose document type and template before generating. If fields are missing, update project settings.',
    stepsTh: ['เปิดหน้า Generate', 'เลือกประเภทเอกสารและ template', 'ตรวจสถานะข้อมูลพร้อม/ขาด', 'ดู preview HTML ที่ escape ข้อมูลแล้ว', 'กดสร้างและดาวน์โหลด DOCX'],
    stepsEn: ['Open Generate.', 'Choose document type and template.', 'Review readiness/missing fields.', 'Check the escaped HTML preview.', 'Generate and download DOCX.'],
    tipsTh: ['version สุดท้ายควรมาจาก RPC ฝั่ง server เพื่อกันเลขชนกัน', 'preview HTML ต้อง escape ค่าที่มาจากผู้ใช้'],
    tipsEn: ['Final version should come from server-side RPC to avoid races.', 'HTML preview must escape user-provided values.'],
    commonProblemsTh: [
      { problem: 'ปุ่มสร้างยังไม่พร้อม', solution: 'ตรวจ missing fields และกลับไปกรอกใน Document Settings' },
    ],
    commonProblemsEn: [
      { problem: 'Generate is not ready.', solution: 'Review missing fields and complete Document Settings.' },
    ],
    relatedTopicIds: ['documents.templates', 'documents.overview'],
  },
  {
    topicId: 'emergency.overview',
    id: 'emergency.overview',
    category: 'emergency',
    slug: 'overview',
    titleTh: 'ระบบฉุกเฉิน',
    titleEn: 'Emergency System',
    summaryTh: 'ใช้ดูข้อมูลสุขภาพ/ฉุกเฉินเฉพาะทีมที่มีสิทธิ์ เพื่อช่วยเหลือได้เร็วและปลอดภัย',
    summaryEn: 'Authorized staff use emergency and health data to respond quickly and safely.',
    audience: ['emergency', 'admin'],
    relatedRoutes: ['/staff/emergency', '/admin/emergency'],
    keywordsTh: ['ฉุกเฉิน', 'สุขภาพ', 'แพ้อาหาร', 'โรคประจำตัว', 'เบอร์ติดต่อฉุกเฉิน'],
    keywordsEn: ['emergency', 'health', 'allergy', 'medical', 'emergency phone'],
    quickHelpTh: 'ใช้เฉพาะเมื่อทำหน้าที่ความปลอดภัยหรือเกิดเหตุจริง และหลีกเลี่ยงการเปิดข้อมูลต่อคนไม่มีสิทธิ์',
    quickHelpEn: 'Use only for safety duties or real incidents, and avoid exposing data to unauthorized people.',
    stepsTh: ['เปิดหน้า Emergency ด้วยบัญชีที่มีสิทธิ์', 'ค้นหาผู้เข้าร่วมหรือทีมงานที่ต้องช่วยเหลือ', 'ดูข้อมูลสำคัญ เช่น แพ้อาหาร โรคประจำตัว เบอร์ฉุกเฉิน', 'บันทึก note เท่าที่จำเป็น'],
    stepsEn: ['Open Emergency with authorized access.', 'Search the participant or staff member needing help.', 'Review key data such as allergies, diseases, and emergency phone.', 'Record only necessary notes.'],
    tipsTh: ['อย่าใช้สีแดงกับข้อมูลที่ไม่ใช่เหตุฉุกเฉินจริงเพื่อไม่ให้ผู้ใช้ล้า', 'มือถือควรเห็นปุ่มโทรหรือ action สำคัญใน 1 tap'],
    tipsEn: ['Avoid overusing red for non-critical information.', 'Mobile should expose call or critical actions in one tap.'],
    commonProblemsTh: [
      { problem: 'เข้า Emergency ไม่ได้', solution: 'ต้องมีสิทธิ์ emergency_staff หรือ admin ให้แอดมินตรวจบทบาท' },
    ],
    commonProblemsEn: [
      { problem: 'Cannot access Emergency.', solution: 'You need emergency_staff or admin access. Ask an admin to check roles.' },
    ],
    relatedTopicIds: ['admin.dashboard', 'staff.login'],
  },
  {
    topicId: 'faq.no-auth-staff',
    id: 'faq.no-auth-staff',
    category: 'faq',
    slug: 'no-auth-staff',
    titleTh: 'ไม่มีบัญชีทีมงาน ใช้ระบบได้ไหม',
    titleEn: 'Can Staff Without an Account Use the System?',
    summaryTh: 'ใช้ได้ในบางเมนู เช่น แก้โปรไฟล์ทีมงาน เช็กชื่อด้วยอีเมล+เบอร์โทร และ QR ส่วนตัว',
    summaryEn: 'Yes for some flows, such as profile verification, email+phone attendance, and personal QR.',
    audience: ['staff'],
    relatedRoutes: ['/staff/profile/verify', '/staff/attendance', '/staff/profile/qr'],
    keywordsTh: ['ไม่มีบัญชี', 'ไม่ login', 'อีเมล เบอร์โทร', 'ทีมงาน'],
    keywordsEn: ['no account', 'no auth', 'email phone', 'staff'],
    quickHelpTh: 'ทีมงานไม่มีบัญชีเข้าสู่ระบบยังยืนยันด้วยอีเมลและเบอร์โทรในบางเมนูได้',
    quickHelpEn: 'Staff without sign-in accounts can still verify by email and phone in supported flows.',
    stepsTh: ['เปิดเมนูที่รองรับการยืนยันตัวตน เช่น เช็กชื่อหรือแก้โปรไฟล์', 'กรอกอีเมลและเบอร์โทร', 'ระบบจำตัวตนไว้ในเครื่องนี้ช่วงเวลาหนึ่ง', 'ล้างตัวตนที่จำไว้ได้เมื่อใช้เครื่องร่วมกับคนอื่น'],
    stepsEn: ['Open a verified flow such as attendance or profile edit.', 'Enter email and phone.', 'The app remembers this device for a limited time.', 'Clear remembered identity if sharing a device.'],
    tipsTh: ['ข้อมูลที่จำไว้ไม่ควรมีอีเมลหรือเบอร์โทรแบบ raw'],
    tipsEn: ['Remembered identity should not store raw email or phone.'],
    commonProblemsTh: [
      { problem: 'เครื่องถามอีเมลซ้ำ', solution: 'ตัวตนที่จำไว้อาจหมดอายุหรือถูกล้าง ให้ยืนยันใหม่' },
    ],
    commonProblemsEn: [
      { problem: 'The device asks for email again.', solution: 'The remembered identity may have expired or been cleared; verify again.' },
    ],
    relatedTopicIds: ['staff-attendance.overview', 'staff.profile-verify'],
  },
  {
    topicId: 'faq.cannot-check-in',
    id: 'faq.cannot-check-in',
    category: 'faq',
    slug: 'cannot-check-in',
    titleTh: 'เช็กชื่อไม่ได้ทำอย่างไร',
    titleEn: 'What If Check-In Does Not Work?',
    summaryTh: 'ตรวจว่า QR ยังเปิดอยู่ กลุ่มเป้าหมายถูกต้อง และใช้ Manual fallback ได้',
    summaryEn: 'Check that the QR is active, target scope is correct, and use manual fallback if needed.',
    audience: ['staff', 'admin'],
    relatedRoutes: ['/staff/attendance', '/admin/staff/attendance'],
    keywordsTh: ['เช็กชื่อไม่ได้', 'สแกนไม่ได้', 'QR หมดอายุ', 'manual'],
    keywordsEn: ['cannot check in', 'scan failed', 'expired QR', 'manual'],
    quickHelpTh: 'ถ้าเช็กชื่อไม่ได้ ให้แอดมินตรวจรอบ Active/เวลา/กลุ่มเป้าหมาย หรือเช็กแบบ Manual',
    quickHelpEn: 'If check-in fails, admin should check Active status/time/target scope or use manual check-in.',
    stepsTh: ['อ่านข้อความ error สั้น ๆ', 'ตรวจว่าใช้ QR ถูกประเภท', 'ให้แอดมินดูสถานะรอบและเวลา', 'ถ้ารีบ ให้ใช้ Manual check-in ก่อน'],
    stepsEn: ['Read the short error message.', 'Confirm the QR type is correct.', 'Ask admin to check session status and time.', 'If urgent, use manual check-in first.'],
    tipsTh: ['วันงานควรมีคนแอดมินสำรองสำหรับ Manual'],
    tipsEn: ['On event day, keep an admin ready for manual fallback.'],
    commonProblemsTh: [
      { problem: 'บัญชีไม่มีสิทธิ์รอบนี้', solution: 'รอบอาจตั้ง target scope ผิด หรือทีมงานอยู่คนละกลุ่ม/ฝ่าย' },
    ],
    commonProblemsEn: [
      { problem: 'Account is not allowed for this session.', solution: 'The target scope may be wrong, or staff belongs to a different group/role.' },
    ],
    relatedTopicIds: ['staff-attendance.session-qr', 'admin-attendance.manual-checkin'],
  },
  {
    topicId: 'faq.qr-difference',
    id: 'faq.qr-difference',
    category: 'faq',
    slug: 'qr-difference',
    titleTh: 'QR รอบเช็กชื่อกับ QR ส่วนตัวต่างกันอย่างไร',
    titleEn: 'Session QR vs Personal QR',
    summaryTh: 'QR รอบเช็กชื่อใช้ให้ทีมงานเช็กชื่อเอง ส่วน QR ส่วนตัวใช้ให้แอดมินสแกนระบุตัวทีมงาน',
    summaryEn: 'Session QR is for staff self check-in. Personal QR is for admin-assisted staff identification.',
    audience: ['staff', 'admin'],
    relatedRoutes: ['/staff/attendance', '/staff/profile/qr', '/admin/staff/attendance'],
    keywordsTh: ['QR ต่างกัน', 'QR รอบ', 'QR ส่วนตัว', 'คิวอาร์'],
    keywordsEn: ['QR difference', 'session QR', 'personal QR'],
    quickHelpTh: 'ถ้าทีมงานสแกนเอง ใช้ QR รอบเช็กชื่อ ถ้าแอดมินสแกนให้ ใช้ QR ส่วนตัวทีมงาน',
    quickHelpEn: 'If staff scans themselves, use session QR. If admin scans staff, use staff personal QR.',
    stepsTh: ['ดูว่าใครเป็นคนสแกน', 'ทีมงานสแกนเอง: ใช้ QR รอบเช็กชื่อ', 'แอดมินสแกนให้: ใช้ QR ส่วนตัวทีมงาน', 'ถ้าสับสน ใช้ Manual check-in เป็น fallback'],
    stepsEn: ['Check who is scanning.', 'Staff self-scan: use session QR.', 'Admin scans staff: use personal QR.', 'If unsure, use manual check-in as fallback.'],
    tipsTh: ['QR ส่วนตัวไม่ควรมีอีเมล เบอร์โทร หรือข้อมูลสุขภาพ'],
    tipsEn: ['Personal QR should not contain email, phone, or health data.'],
    commonProblemsTh: [
      { problem: 'สแกน QR ส่วนตัวในหน้าทีมงานแล้วไม่เช็กชื่อ', solution: 'ถูกต้องแล้ว QR ส่วนตัวต้องให้แอดมินสแกนในรอบเช็กชื่อ' },
    ],
    commonProblemsEn: [
      { problem: 'Scanning personal QR on staff self-scan does not work.', solution: 'That is expected. Personal QR must be scanned by admin inside a session.' },
    ],
    relatedTopicIds: ['staff-attendance.session-qr', 'staff-attendance.personal-qr', 'admin-attendance.scan-staff-qr'],
  },
  {
    topicId: 'faq.attendance-time-error',
    id: 'faq.attendance-time-error',
    category: 'faq',
    slug: 'attendance-time-error',
    titleTh: 'เวลาเช็กชื่อผิดวัน/ผิดเวลาเกิดจากอะไร',
    titleEn: 'Why Is Attendance Time Wrong?',
    summaryTh: 'มักเกิดจากการ treat ค่า datetime-local เป็น UTC หรือเติม Z ผิด ต้องแสดงผลด้วย Asia/Bangkok',
    summaryEn: 'Usually caused by treating datetime-local as UTC or appending Z incorrectly. Display with Asia/Bangkok.',
    audience: ['admin'],
    relatedRoutes: ['/admin/staff/attendance'],
    keywordsTh: ['เวลา', 'timezone', 'ผิดวัน', 'เวลาไทย', 'UTC', 'บวก 7'],
    keywordsEn: ['time', 'timezone', 'wrong day', 'Bangkok', 'UTC', '+7'],
    quickHelpTh: 'กรอกเวลาไทยตามเครื่อง ห้ามบวก/ลบ 7 ชั่วโมงเอง และตรวจด้วย format Asia/Bangkok',
    quickHelpEn: 'Enter local Thailand time, do not manually add/subtract 7 hours, and display using Asia/Bangkok.',
    stepsTh: ['กรอก datetime-local จาก browser', 'แปลงเป็น ISO ด้วย new Date(value).toISOString()', 'เก็บใน Supabase เป็น timestamptz', 'แสดงผลด้วย timeZone Asia/Bangkok'],
    stepsEn: ['Enter datetime-local from the browser.', 'Convert to ISO using new Date(value).toISOString().', 'Store in Supabase as timestamptz.', 'Display with timeZone Asia/Bangkok.'],
    tipsTh: ['ถ้าใส่ 21 พ.ค. 22:25 แล้วเห็น 22 พ.ค. 05:25 แปลว่าถูก shift เป็น UTC ผิด'],
    tipsEn: ['If 21 May 22:25 becomes 22 May 05:25, it was shifted as UTC incorrectly.'],
    commonProblemsTh: [
      { problem: 'เวลาเลื่อน +7 ชั่วโมง', solution: 'ตรวจว่ามีการ append Z ให้ datetime-local หรือ parse เป็น UTC โดยไม่ตั้งใจหรือไม่' },
    ],
    commonProblemsEn: [
      { problem: 'Time shifts +7 hours.', solution: 'Check for accidental Z append or UTC parsing of datetime-local values.' },
    ],
    relatedTopicIds: ['admin-attendance.create-session', 'admin-attendance.late-after'],
  },
  {
    topicId: 'faq.edit-approval-delay',
    id: 'faq.edit-approval-delay',
    category: 'faq',
    slug: 'edit-approval-delay',
    titleTh: 'แก้ไขข้อมูลแล้วทำไมยังไม่เปลี่ยนทันที',
    titleEn: 'Why Did My Edit Not Apply Immediately?',
    summaryTh: 'ข้อมูลบางประเภทต้องรอแอดมินตรวจสอบและอนุมัติก่อน เพื่อป้องกันข้อมูลผิดคน',
    summaryEn: 'Some fields require admin approval to prevent wrong-profile or unsafe updates.',
    audience: ['participant', 'staff'],
    relatedRoutes: ['/edit', '/staff/profile/verify'],
    keywordsTh: ['รออนุมัติ', 'คำขอแก้ไข', 'ยังไม่เปลี่ยน', 'approval'],
    keywordsEn: ['approval', 'edit request', 'not updated', 'pending'],
    quickHelpTh: 'หลังส่งคำขอ ระบบจะรอแอดมินอนุมัติก่อนอัปเดตข้อมูลจริง',
    quickHelpEn: 'After submission, the app waits for admin approval before applying changes.',
    stepsTh: ['ส่งคำขอแก้ไข', 'รอแอดมินตรวจข้อมูลเก่าและใหม่', 'แอดมินอนุมัติหรือปฏิเสธ', 'ข้อมูลจริงจะเปลี่ยนหลังอนุมัติ'],
    stepsEn: ['Submit the edit request.', 'Admin reviews old and new data.', 'Admin approves or rejects.', 'The real profile updates after approval.'],
    tipsTh: ['ถ้าต้องแก้ด่วน ให้แจ้งแอดมินพร้อมชื่อและข้อมูลที่ต้องแก้'],
    tipsEn: ['For urgent changes, contact an admin with your name and requested correction.'],
    commonProblemsTh: [
      { problem: 'ส่งผิดข้อมูล', solution: 'แก้ค่าที่ต้องการแล้วส่งคำขอใหม่ หรือแจ้งแอดมินให้ปฏิเสธคำขอเก่า' },
    ],
    commonProblemsEn: [
      { problem: 'I submitted the wrong data.', solution: 'Submit a corrected request or ask admin to reject the old one.' },
    ],
    relatedTopicIds: ['participant.edit-info', 'staff.profile-verify'],
  },
];
